# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Github Pages - dl-ui-migration

on:
  push:
    branches:
      - newMigration

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1
      with:
          persist-credentials: false
          
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '18.16.0'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        
 # Install required tools (zip and split)
    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y zip

      # Split the large file (app.bundle.js) into smaller parts (e.g., 100MB each)
    - name: Split app.bundle.js into smaller parts
      run: |
        split -b 50M ./dist/app.bundle.js "./dist/app.bundle.js.part."  # Split the file located in the 'dist' folder
        rm ./dist/app.bundle.js

      # Zip the parts into a .zip archive
    - name: Create a zip file from the parts
      run: |
        zip ./dist/app.bundle.js.zip ./dist/app.bundle.js.part.*  # Zip the parts into the 'dist' folder
    
    - name: Set Git Identity
      run: |
        git config --global user.email "it.software@danliris.com"
        git config --global user.name "danliris"
        
    - name: Deploy to GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: JamesIves/github-pages-deploy-action@132898c54c57c7cc6b80eb3a89968de8fc283505
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        # This is the branch you wish to deploy to, for example gh-pages or docs.
        BRANCH: master
        # The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.
        FOLDER: ./dist
        # Allows you to speicfy a different repository path so long as you have permissions to push to it. This should be formatted like so: JamesIves/github-pages-deploy-action
        REPOSITORY_NAME: danliris/danliris.github.io
        # Depending on the repository permissions you may need to provide the action with a GitHub personal access token instead of the provided GitHub token in order to deploy. This should be stored as a secret.
        ACCESS_TOKEN: ${{ secrets.GithubPages }}
        
 # Step 6: Clean up the split parts and zip file after deployment (optional)
    - name: Clean up
      run: |
        rm ./dist/app.bundle.js.part.*  # Remove the split parts
        rm ./dist/app.bundle.js.zip  # Remove the zip file
